### ISSUE TITLE
ADD README.md

### ISSUE THREAD

**Issue by siavashMehran** [yousefshalby/django_job_search_app_django#1]
hey . . . 
I've seen your projects and cloned this and i really liked it
but the thing is people don't just go around and get themselves into the whole process of cloning and installing and running and shit

you shoud document your projects by adding a descriptive README file with clear instructions

if you ever needed help count on me 
I'm just like you

**Comment by yousefshalby** [comment]
Thank you for your advice and I will start to work on it
